### ISSUE TITLE
Icons misaligned

### ISSUE THREAD

**Issue by cyberalien** [Templarian/MaterialDesignLight#6]
I've noticed many icons are misaligned, that is they have more empty space on one side instead of being centered.

For example "cancel" and "briefcase" icons on 24x24 grid with icon template in background:
![misalignment](https://user-images.githubusercontent.com/822287/49791278-d185c180-fd38-11e8-877b-c3501c1f4e57.png)

Both icons have 3 px spacing on right and 2px spacing on left. Is it intentional or a bug?

**Comment by Templarian** [comment]
This is completely intentional design. The team actually has some design guidelines that we're working on to better explain this. Every single icon is designed assuming 23x23 area.

![image](https://user-images.githubusercontent.com/338885/49850827-a46ef880-fda4-11e8-8d81-2e7f80b458b2.png)

Sorry, while were open sourcing everything we're still working on docs and guidelines. The core contributor team has more than has been said publicly.

For those using SVG you can set the SVG viewbox to clip this, but for the webfont we'll be using a 24x24 with the above offset.

**Comment by Templarian** [comment]
Note: Some of the icons are being completely redesigned to fit the new guidelines a very large majority are simply moving every point down and to the left to produce a `1dp` width line. 😃

**Comment by ggedde** [comment]
@Templarian Is there any more information on this? 
Why the 23x23 and not 24x24?
What is the 1dp width line and what importance does it have?

Shouldn't they be compatible with the main icon library. Meaning I should be able to swap out my main icon with a light icon and not have to adjust the viewbox? 

I am very curious what the reasoning for this is. 
Any links or documentation you can share regarding these new guidelines.
Thanks
